steps:
  - name: "gcr.io/cloud-builders/docker"
    id: Build backend
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/kube-test/backend:$SHORT_SHA",
        "backend",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: Build frontend
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/$PROJECT_ID/kube-test/frontend:$SHORT_SHA",
        "frontend",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: Push images to container registry
    entrypoint: bash
    args:
      - "-c"
      - |
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/kube-test/backend:$SHORT_SHA
        docker push asia-south1-docker.pkg.dev/$PROJECT_ID/kube-test/frontend:$SHORT_SHA
  - name: "gcr.io/cloud-builders/gcloud"
    id: Update kustomize templates and create output yaml
    entrypoint: "bash"
    args:
      - "-c"
      - |
        git clone --depth 1 https://github.com/aabedraba/kube-test-devops
        sed -i "s/SHORT_SHA/$SHORT_SHA/g" kube-test-devops/kubernetes/kustomization.yaml
        sed -i "s/PROJECT_ID/$PROJECT_ID/g" kube-test-devops/kubernetes/kustomization.yaml
        kustomize build kube-test-devops/kubernetes -o output-manifest.yaml
  - name: "gcr.io/cloud-builders/kubectl"
    id: Create argoCD components
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials --zone "asia-south1" "$PROJECT_ID-gke"
        kubectl create namespace argocd --dry-run=client -o yaml \
        | grep -v creationTimestamp | kubectl apply -f -
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - name: "gcr.io/cloud-builders/gke-deploy"
    id: Deploy images
    args:
      [
        "apply",
        "--filename=output-manifest.yaml",
        "--location=asia-south1",
        "--cluster=$PROJECT_ID-gke",
      ]
